name = "stock-monitoring-bot-discord-webhook-dev"
main = "src/index.ts"
compatibility_date = "2024-07-31"

[build]
command = ""

[env.dev]
name = "stock-monitoring-bot-discord-webhook-dev"

[vars]
AWS_REGION = "ap-northeast-1"